"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { Activity, BookOpen, RefreshCw, ShieldCheck, UsersRound } from "lucide-react";
import LinkedInEventManager from "./linkedin-event-manager";
import { workspaceRequest } from "@/lib/workspace-client";
import type { AdminAccount, AdminData } from "@/lib/admin-model";
const labels={suspend:"Suspend account",restore:"Restore account",revoke_sessions:"Sign out all sessions"};
type Action=keyof typeof labels;
export default function AdminDashboard({query}:{query:string}) {
  const [data,setData]=useState<AdminData|null>(null);
  const [tab,setTab]=useState("Overview");
  const [role,setRole]=useState("");
  const [status,setStatus]=useState("");
  const [loading,setLoading]=useState(false);
  const [error,setError]=useState("");
  const [message,setMessage]=useState("");
  const [pending,setPending]=useState<{account:AdminAccount;action:Action}|null>(null);
  const [reason,setReason]=useState("");
  const [saving,setSaving]=useState(false);
  const confirmRef=useRef<HTMLFormElement>(null);
  useEffect(()=>{if(pending){confirmRef.current?.scrollIntoView({block:"center",behavior:"smooth"});confirmRef.current?.querySelector("textarea")?.focus();}},[pending]);
  const refresh=useCallback(async(signal?:AbortSignal)=>{
    setLoading(true);try{setData(await workspaceRequest<AdminData>("/api/admin",{signal}));setError("");}catch(error){if(!signal?.aborted)setError(error instanceof Error?error.message:"Could not load administration.");}finally{if(!signal?.aborted)setLoading(false);}
  },[]);
  useEffect(()=>{const controller=new AbortController();const frame=requestAnimationFrame(()=>void refresh(controller.signal));return()=>{controller.abort();cancelAnimationFrame(frame);};},[refresh]);
  const perform=async(event:React.FormEvent)=>{
    event.preventDefault();if(!pending||saving)return;
    setSaving(true);setError("");
    try{await workspaceRequest("/api/admin",{method:"PATCH",body:JSON.stringify({accountId:pending.account.id,action:pending.action,reason})});setMessage(`${labels[pending.action]} completed for ${pending.account.name}.`);setPending(null);setReason("");await refresh();}catch(error){setError(error instanceof Error?error.message:"Action failed.");}finally{setSaving(false);}
  };
  const activeTab=tab==="Overview" && query.trim()?"Accounts":tab;
  const accounts=(data?.accounts??[]).filter(account=>(!role||account.role===role)&&(!status||(status==="suspended"?account.suspended:!account.suspended))&&[account.name,account.id,account.email,account.role].join(" ").toLowerCase().includes(query.trim().toLowerCase()));
  const activity=(data?.activity??[]).filter(item=>[item.actor,item.target,labels[item.action as Action]??item.action,item.reason].join(" ").toLowerCase().includes(query.trim().toLowerCase()));
  const stats=data?[ ["Accounts",data.metrics.accounts,"Demo sign-in roster"],["Active sessions",data.metrics.activeSessions,"Unexpired sign-in sessions"],["Saved portfolios",data.metrics.portfolios,"Account portfolio records"],["Shared student portfolios",data.metrics.sharedPortfolios,"Visible in faculty directory"] ]:[];
  return <div className="admin-workspace"><div className="page-heading"><div><p className="eyebrow">Campus administration</p><h1>Admin dashboard</h1><p>Manage account access, review portfolio activity and monitor the workspace.</p></div><button className="secondary-button" disabled={loading} onClick={()=>void refresh()}><RefreshCw size={16}/>{loading?"Refreshing…":"Refresh data"}</button></div><div className="security-banner"><ShieldCheck size={24}/><div><strong>Local demo workspace</strong><p>Admin actions persist in the database. University sign-in and the official roster still need connecting.</p></div></div><div className="settings-tabs" role="tablist" aria-label="Admin dashboard sections">{["Overview","Accounts","Activity","Events"].map(item=><button key={item} role="tab" aria-selected={activeTab===item} aria-controls="admin-panel" className={activeTab===item?"active":""} onClick={()=>setTab(item)}>{item}</button>)}</div>{error&&<p className="provider-notice" role="alert">{error}<button className="text-button" onClick={()=>void refresh()}>Retry</button></p>}{message&&<p className="provider-notice" role="status">{message}</p>}{loading&&!data&&<p role="status">Loading admin data…</p>}{data&&<><p className="admin-updated">Updated {new Date(data.updatedAt).toLocaleTimeString("en-IN",{timeZone:"Asia/Kolkata",hour:"2-digit",minute:"2-digit"})} IST · Mock student profiles are separate from sign-in accounts.</p><div id="admin-panel" role="tabpanel" aria-label={activeTab}>
    {activeTab==="Overview"&&<><div className="admin-stat-grid">{stats.map(([label,value,note])=><article className="panel admin-stat" key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</div><div className="admin-overview-grid"><section className="panel admin-section"><h2><UsersRound size={19}/> Account access</h2><p>{data.accounts.filter(account=>account.suspended).length} suspended accounts · {data.accounts.filter(account=>account.role==="Student").length} student accounts · {data.accounts.filter(account=>account.role==="Faculty").length} faculty accounts</p><button className="secondary-button" onClick={()=>setTab("Accounts")}>Manage accounts</button></section><section className="panel admin-section"><h2><BookOpen size={19}/> Portfolios & engagement</h2><p>{data.metrics.bookmarks} saved hackathons · {data.metrics.teamRequests} pending team requests</p></section><section className="panel admin-section"><h2><Activity size={19}/> Administrative activity</h2><p>{data.activity.length?`${data.activity.length} recent actions recorded. Most recent: ${labels[data.activity[0].action as Action]??data.activity[0].action}.`:"No administrative changes recorded yet."}</p><button className="secondary-button" onClick={()=>setTab("Activity")}>View audit log</button></section><section className="panel admin-section"><h2>Deployment readiness</h2><ul><li>Server role checks: active</li><li>Account suspension and session revocation: active</li><li>Persistent admin audit log: active</li><li>University SSO and official roster: not connected</li></ul></section></div></>}
    {activeTab==="Accounts"&&<><div className="student-filters"><label>Role<select value={role} onChange={e=>setRole(e.target.value)}><option value="">All roles</option>{["Student","Faculty","Admin"].map(value=><option key={value}>{value}</option>)}</select></label><label>Account status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="active">Active</option><option value="suspended">Suspended</option></select></label></div><p role="status">{accounts.length} matching accounts · Search by name, ID or email above.</p><div className="admin-table-scroll"><table className="admin-account-table"><thead><tr><th>Account</th><th>Role & access</th><th>Portfolio</th><th>Sessions</th><th>Actions</th></tr></thead><tbody>{accounts.map(account=><tr key={account.id}><td><strong>{account.name}</strong><small>{account.id}</small><small>{account.email}</small></td><td>{account.role}<small>{account.suspended?"Suspended":"Active"}</small></td><td>{account.portfolioUpdatedAt?`${account.projects} projects · ${account.achievements} achievements`:"Not created"}<small>{account.sharedWithFaculty?"Shared with faculty":"Private"}</small></td><td>{account.sessions}</td><td>{account.role==="Admin"?<small>Protected admin account</small>:<div className="admin-account-actions"><button className="secondary-button" onClick={()=>{setPending({account,action:account.suspended?"restore":"suspend"});setReason("");}}>{account.suspended?"Restore":"Suspend"}</button><button className="text-button" disabled={!account.sessions} onClick={()=>{setPending({account,action:"revoke_sessions"});setReason("");}}>Sign out sessions</button></div>}</td></tr>)}</tbody></table></div>{!accounts.length&&<p>No accounts match the current search and filters.</p>}</>}
    {activeTab==="Events"&&<LinkedInEventManager/>}
    {activeTab==="Activity"&&<section className="panel admin-section"><h2>Audit log</h2><p>Latest 100 administrative actions. Portfolio content and session tokens are not logged.</p>{activity.map(item=><article className="admin-audit-item" key={item.id}><strong>{labels[item.action as Action]??item.action} · {item.target}</strong><p>{item.reason}</p><small>{item.actor} · {new Date(item.createdAt).toLocaleString("en-IN",{timeZone:"Asia/Kolkata"})} IST</small></article>)}{!activity.length&&<p>No audit entries match this view.</p>}</section>}
  </div></>}{pending&&<form ref={confirmRef} className="panel admin-confirm" onSubmit={event=>void perform(event)} aria-label="Confirm account action"><h2>{labels[pending.action]}: {pending.account.name}</h2><p>{pending.action==="suspend"?"This blocks sign-in and signs out existing sessions. You can restore access later; saved portfolios remain intact.":pending.action==="restore"?"This restores sign-in access. The account will need to sign in again.":"Existing sessions will be signed out. The account can sign in again."}</p><label>Reason<textarea required minLength={3} maxLength={300} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain this access change for the audit log"/></label><div className="portfolio-editor-actions"><button className="primary-button" disabled={saving}>{saving?"Applying…":"Confirm action"}</button><button className="secondary-button" type="button" disabled={saving} onClick={()=>setPending(null)}>Cancel</button></div></form>}</div>;
}
