"use client";
import {useEffect,useRef,useState,type CSSProperties} from "react";
import {ArrowUpRight,ArrowDown,Mountain,Radio,Layers3,ShieldCheck,Activity,Menu,X,Sun,Moon} from "lucide-react";
import * as THREE from "three";
import "./landing.css";
import Brand, {BrandMark, BrandWordmark} from "./Brand";
function Terrain({lightMode}:{lightMode:boolean}){
 const host=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!host.current)return;const container=host.current;let renderer:THREE.WebGLRenderer;
 try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});}catch{container.dataset.fallback="true";return;}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;container.appendChild(renderer.domElement);
 const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(lightMode?0xeff2ec:0x20272c,.035);const camera=new THREE.PerspectiveCamera(36,1,.1,100);camera.position.set(12,10,17);camera.lookAt(0,1,0);const terrain=new THREE.Group();scene.add(terrain);
 const height=(x:number,z:number)=>{const peak=(cx:number,cz:number,h:number,w:number)=>h*Math.exp(-((x-cx)**2+(z-cz)**2)/w);return peak(-1,0,5.3,7)+peak(3,1,3.4,4)+peak(-4,-2,2.9,4)+peak(0,-4,2,5)+Math.sin(x*3+z)*Math.cos(z*2.4)*.21*Math.max(0,1-Math.hypot(x,z)/11);};
 const geo=new THREE.PlaneGeometry(19,16,100,84);geo.rotateX(-Math.PI/2);const pos=geo.attributes.position;for(let i=0;i<pos.count;i++)pos.setY(i,height(pos.getX(i),pos.getZ(i)));geo.computeVertexNormals();
 const mesh=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:lightMode?0x577947:0x344a34,roughness:.88,metalness:.25,flatShading:true}));mesh.castShadow=true;mesh.receiveShadow=true;terrain.add(mesh);
 const wire=new THREE.Mesh(geo,new THREE.MeshBasicMaterial({color:0x87a66a,wireframe:true,transparent:true,opacity:.105}));wire.position.y=.015;terrain.add(wire);const grid=new THREE.GridHelper(32,48,lightMode?0x98ac89:0x43533f,lightMode?0xcbd4c3:0x2d3832);grid.position.y=-.3;terrain.add(grid);
 scene.add(new THREE.AmbientLight(0xbac9ae,1.1));const light=new THREE.DirectionalLight(0xd5e9bd,3);light.position.set(-5,12,5);light.castShadow=true;light.shadow.mapSize.set(1024,1024);Object.assign(light.shadow.camera,{left:-12,right:12,top:12,bottom:-12});scene.add(light);const rim=new THREE.PointLight(0x7ba65e,60,30);rim.position.set(4,6,-7);scene.add(rim);
 const rings:THREE.Mesh[]=[];[[-3,2],[2,2],[4,-1],[-2,-3],[0,4]].forEach(([x,z],i)=>{const color=i===1?0xff9c58:0xa1c17b;const marker=new THREE.Mesh(new THREE.SphereGeometry(.075,12,12),new THREE.MeshBasicMaterial({color}));marker.position.set(x,height(x,z)+.14,z);terrain.add(marker);const pole=new THREE.Mesh(new THREE.CylinderGeometry(.012,.012,1.1),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.6}));pole.position.copy(marker.position);pole.position.y+=.55;terrain.add(pole);const ring=new THREE.Mesh(new THREE.RingGeometry(.18,.21,40),new THREE.MeshBasicMaterial({color,side:THREE.DoubleSide,transparent:true,opacity:.7}));ring.rotation.x=-Math.PI/2;ring.position.copy(marker.position);terrain.add(ring);rings.push(ring);});
 const scanMaterial=new THREE.ShaderMaterial({
   uniforms:{scanRadius:{value:0}},transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,
   vertexShader:`varying vec3 terrainPosition; void main(){terrainPosition=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`,
   fragmentShader:`uniform float scanRadius; varying vec3 terrainPosition; void main(){float distanceFromCenter=length(terrainPosition.xz);float band=1.0-smoothstep(0.0,0.38,abs(distanceFromCenter-scanRadius));float fade=1.0-smoothstep(8.0,12.0,scanRadius);gl_FragColor=vec4(0.56,0.78,0.35,band*fade*0.38);}`
 });
 const scan=new THREE.Mesh(geo,scanMaterial);scan.position.y=.035;terrain.add(scan);
 const reduced=matchMedia("(prefers-reduced-motion: reduce)");let frame=0,rotation=-.3,target=-.3,last=0;const scroll=()=>{target=-.3+Math.min(1,window.scrollY/Math.max(1,window.innerHeight*1.1))*Math.PI*2;};const resize=()=>{camera.aspect=container.clientWidth/container.clientHeight;camera.updateProjectionMatrix();renderer.setSize(container.clientWidth,container.clientHeight);};const observer=new ResizeObserver(resize);observer.observe(container);resize();scroll();window.addEventListener("scroll",scroll,{passive:true});
 let pointerX=0,pointerY=0,elapsed=0,visible=true;
 const pointer=(event:PointerEvent)=>{if(event.pointerType!=="mouse")return;pointerX=event.clientX/window.innerWidth-.5;pointerY=event.clientY/window.innerHeight-.5;};
 const resetPointer=()=>{pointerX=0;pointerY=0;};
 window.addEventListener("pointermove",pointer,{passive:true});document.documentElement.addEventListener("pointerleave",resetPointer);
 const render=(time:number)=>{
   frame=0;const dt=Math.min((time-last)/1000,.05);last=time;elapsed+=dt;
   const ease=1-Math.exp(-dt*5);rotation+=(target-rotation)*ease;
   terrain.rotation.y=reduced.matches?-.3:rotation+Math.sin(elapsed*.22)*.08;
   camera.position.x+=((12+(reduced.matches?0:pointerX*1.8))-camera.position.x)*ease;
   camera.position.y+=((10+(reduced.matches?0:pointerY*.9))-camera.position.y)*ease;camera.lookAt(0,1,0);
   scan.visible=!reduced.matches;scanMaterial.uniforms.scanRadius.value=(elapsed*1.5)%13;
   rings.forEach((r,i)=>{const phase=(elapsed*.45+i*.2)%1;r.scale.setScalar(reduced.matches?1:1+phase*3.5);(r.material as THREE.MeshBasicMaterial).opacity=reduced.matches?.7:(1-phase)*.8;});
   renderer.render(scene,camera);
   if(visible&&!document.hidden&&!reduced.matches)frame=requestAnimationFrame(render);
 };
 const resume=()=>{if(visible&&!document.hidden&&!frame){last=performance.now();frame=requestAnimationFrame(render);}};
 const visibility=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible)resume();else{cancelAnimationFrame(frame);frame=0;}},{rootMargin:"100px"});visibility.observe(container);
 const tabVisibility=()=>{if(document.hidden){cancelAnimationFrame(frame);frame=0;}else resume();};
 document.addEventListener("visibilitychange",tabVisibility);reduced.addEventListener("change",resume);window.addEventListener("resize",resume);resume();
 return()=>{cancelAnimationFrame(frame);observer.disconnect();visibility.disconnect();window.removeEventListener("scroll",scroll);window.removeEventListener("pointermove",pointer);document.documentElement.removeEventListener("pointerleave",resetPointer);document.removeEventListener("visibilitychange",tabVisibility);reduced.removeEventListener("change",resume);window.removeEventListener("resize",resume);scene.traverse(obj=>{if(obj instanceof THREE.Mesh||obj instanceof THREE.LineSegments){obj.geometry.dispose();(Array.isArray(obj.material)?obj.material:[obj.material]).forEach(m=>m.dispose());}});renderer.dispose();renderer.domElement.remove();};},[lightMode]);
 return <div className="nt-terrain" ref={host} role="img" aria-label="Three-dimensional mountain terrain with glowing sensor nodes"><div className="nt-fallback"><Mountain size={180}/><p>Terrain visualization unavailable. Explore the system below.</p></div></div>;
}
function BotanicalBackground(){
 return <div className="nt-botanical" aria-hidden="true">
   <div className="nt-leaf-field">{Array.from({length:14},(_,i)=><div className="nt-leaf-drift" key={i} style={{"--leaf-x":`${(i*31+7)%100}%`,"--leaf-duration":`${22+(i%5)*5}s`,"--leaf-delay":`${-i*4.7}s`,"--leaf-size":`${14+(i%4)*8}px`,"--leaf-opacity":.13+(i%3)*.06} as CSSProperties}><svg className="nt-falling-leaf" viewBox="0 0 50 80"><path d="M25 72C-6 47 0 17 42 3C51 35 48 57 25 72Z"/><path className="nt-leaf-vein" d="M23 78Q26 45 40 9M27 54L10 39M31 39L41 28"/></svg></div>)}</div>
   <div className="nt-plants">{[0,1,2,3].map(i=><svg key={i} className={`nt-plant nt-plant-${i}`} viewBox="0 0 200 420"><g className="nt-frond"><path className="nt-stem" d="M100 430Q65 245 119 24"/>{[0,1,2,3,4,5].map(j=><g key={j} transform={`translate(${106-j*4} ${65+j*48}) scale(${.55+j*.085})`}><path d="M0 18Q-63 16-79-39Q-20-40 0 18Z"/><path d="M-2 36Q58 29 78-21Q24-28-2 36Z"/><path className="nt-leaf-vein" d="M-2 18L-67-31M0 36L65-14"/></g>)}</g></svg>)}</div>
 </div>;
}
function SignalVisual({stage}:{stage:string}){
 return <div className={"nt-signal-visual nt-stage-"+stage} aria-hidden="true">
   {stage==="01"?<><div className="nt-wave-grid"/><svg viewBox="0 0 300 100"><path className="nt-wave-track" d="M0 52H35L43 47 51 58 65 42 78 62 92 48 110 52H130L139 27 150 78 160 12 173 87 184 35 195 56 210 48 225 52H300"/><path className="nt-wave-flow" d="M0 52H35L43 47 51 58 65 42 78 62 92 48 110 52H130L139 27 150 78 160 12 173 87 184 35 195 56 210 48 225 52H300"/></svg><span className="nt-viz-label">TERRAIN SIGNAL / SIMULATION</span></>:stage==="02"?<><svg viewBox="0 0 300 100"><g className="nt-network-lines"><path d="M20 20H80L130 50H170L220 20H280M20 80H80L130 50M170 50L220 80H280M20 50H280"/></g><g className="nt-data-flow"><path d="M20 20H80L130 50H170L220 20H280M20 80H80L130 50H170L220 80H280M20 50H280"/></g><rect className="nt-core" x="132" y="32" width="36" height="36" rx="8"/><text x="150" y="54" textAnchor="middle">AI</text></svg><span className="nt-viz-label">PATTERNS → INTELLIGENCE</span></>:<><div className="nt-radar"><i/><i/><i/><b/><span/></div><span className="nt-viz-label">SIGNAL → AWARENESS</span></>}
 </div>;
}
export default function NexTerra(){const [lightMode,setLightMode]=useState(true);const [motionPaused,setMotionPaused]=useState(false);const [menu,setMenu]=useState(false);const [modal,setModal]=useState(false);const reveal=useRef<HTMLElement>(null);const dialog=useRef<HTMLDialogElement>(null);
useEffect(()=>{const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("nt-visible");obs.unobserve(e.target);}}),{threshold:.25});if(reveal.current)obs.observe(reveal.current);document.querySelectorAll(".nt-section-head,.nt-cards article,.nt-mission").forEach(el=>{el.classList.add("nt-reveal-ready");obs.observe(el);});return()=>obs.disconnect();},[]);
useEffect(()=>{const frame=requestAnimationFrame(()=>{try{const saved=localStorage.getItem("nexterra-theme");if(saved)setLightMode(saved==="light");}catch{/* Storage can be unavailable in private browsing. */}});return()=>cancelAnimationFrame(frame);},[]);
const toggleTheme=()=>{const next=!lightMode;setLightMode(next);try{localStorage.setItem("nexterra-theme",next?"light":"dark");}catch{/* Theme still works without storage. */}};
useEffect(()=>{if(modal)dialog.current?.showModal();else dialog.current?.close();},[modal]);
return <main className={`nt-page${motionPaused?" nt-motion-paused":""}${lightMode?" nt-light":""}`}><BotanicalBackground/><header className="nt-header"><a href="#" className="nt-logo" aria-label="NexTerra home"><Brand/></a><nav className={menu?"nt-nav nt-open":"nt-nav"} aria-label="Main navigation"><a href="#technology" onClick={()=>setMenu(false)}>Technology</a><a href="#system" onClick={()=>setMenu(false)}>How it works</a><a href="#mission" onClick={()=>setMenu(false)}>Our mission</a></nav><button className="nt-theme-toggle" onClick={toggleTheme} aria-label={lightMode?"Switch to dark mode":"Switch to light mode"} title={lightMode?"Switch to dark mode":"Switch to light mode"}>{lightMode?<Moon size={18}/>:<Sun size={18}/>}</button><button className="nt-contact" onClick={()=>setModal(true)}>Let’s talk <ArrowUpRight size={16}/></button><button className="nt-menu" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
<section className="nt-hero"><Terrain lightMode={lightMode}/><div className="nt-hero-shade"/><div className="nt-hero-copy"><div className="nt-eyebrow"><span className="nt-dot"/> INTELLIGENCE ABOVE. SAFETY BELOW.</div><h1>Read the earth.<br/>Protect what<br/><em>matters.</em></h1><p>When the ground starts to shift,<br/>every second makes a difference.<br/>See the signs. Stay ahead.</p><a className="nt-primary" href="#technology">Explore the technology <ArrowUpRight size={18}/></a></div><div className="nt-coordinate">27°42′ N &nbsp; 85°19′ E <span>HIMALAYAN TERRAIN / DIGITAL TWIN</span></div><div className="nt-sensor"><span className="nt-dot"/> SENSOR NODE — 04<div>Listening to the landscape.</div><small>ILLUSTRATIVE SENSOR NETWORK</small></div><div className="nt-risk"><span/> GROUND MOVEMENT <b>Early signals. Earlier action.</b></div><div className="nt-hero-bottom"><a href="#technology"><span className="nt-scroll"><ArrowDown size={16}/></span> SCROLL TO DISCOVER</a><span>BUILT FOR A WORLD IN MOTION</span><span className="nt-index">01 / 04</span></div></section>
<div className="nt-ticker"><div className="nt-ticker-track">{[0,1].map(copy=><div className="nt-strip" key={copy} aria-hidden={copy===1?true:undefined}><span>CONNECTED SENSORS</span><i>+</i><span>PREDICTIVE INTELLIGENCE</span><i>+</i><span>EARLIER WARNINGS</span><i>=</i><strong>MORE TIME TO ACT <ArrowUpRight size={15}/></strong></div>)}</div></div>

<section className="nt-intro" id="technology" ref={reveal}><div className="nt-eyebrow">01 — THE NEXT LAYER OF PROTECTION</div><div className="nt-brand-reveal"><div className="nt-brand-emblem"><BrandMark/></div><h2 aria-label="NexTerra"><BrandWordmark/></h2><div className="nt-brand-motto">PREDICTING NATURE. PROTECTING LIVES.</div><p>AI-Powered Landslide Early Warning &amp; Risk Monitoring.</p></div><div className="nt-intro-bottom"><p>The earth speaks before it moves.<br/>We’re building the intelligence to listen.</p><span>From remote hillsides to vulnerable communities, NexTerra connects ground-level sensing with AI-driven insights to turn subtle changes into actionable awareness.</span></div></section>
<section className="nt-system" id="system"><div className="nt-section-head"><div><div className="nt-eyebrow">02 — FROM SIGNAL TO SAFETY</div><h2>A connected system.<br/>A clearer picture.</h2></div><p>Intelligence at every layer.<br/>Awareness at every moment.</p></div><div className="nt-cards">{[{icon:Radio,n:"01",title:"Sense the shift.",text:"Distributed IoT nodes track soil moisture, ground movement, and the conditions that can precede slope failure.",tag:"GROUND-LEVEL AWARENESS"},{icon:Layers3,n:"02",title:"Connect the signals.",text:"AI brings sensor patterns together, helping teams understand changing terrain and identify emerging risk.",tag:"AI-POWERED RISK INSIGHTS"},{icon:ShieldCheck,n:"03",title:"Make time to act.",text:"Clear, timely risk information helps local teams evaluate threats and coordinate a response before conditions escalate.",tag:"HUMAN-CENTERED WARNINGS"}].map(({icon:Icon,...c})=><article key={c.n}><div className="nt-card-top"><Icon size={30} strokeWidth={1.3}/><span>{c.n}</span></div><SignalVisual stage={c.n}/><h3>{c.title}</h3><p>{c.text}</p><div className="nt-card-tag">{c.tag}<ArrowUpRight size={15}/></div></article>)}</div></section>
<section className="nt-mission" id="mission"><div className="nt-mission-orbits" aria-hidden="true"><i/><i/><i/></div><div className="nt-eyebrow">03 — WHY WE’RE HERE</div><Activity className="nt-mission-icon" size={75} strokeWidth={.8}/><h2><span className="nt-line-mask"><span>A safer future starts</span></span><span className="nt-line-mask"><span>with an <em>earlier signal.</em></span></span></h2><p>Technology should protect the places we call home.<br/>Let’s build a more resilient world, from the ground up.</p><button className="nt-primary" onClick={()=>setModal(true)}>Start a conversation <ArrowUpRight size={18}/></button></section><footer className="nt-footer"><a className="nt-logo" href="#" aria-label="NexTerra home"><Brand/></a><span>PREDICTING NATURE. PROTECTING LIVES.</span><button className="nt-motion-toggle" aria-pressed={motionPaused} onClick={()=>setMotionPaused(!motionPaused)}>{motionPaused?"▶ Resume interface motion":"Ⅱ Pause interface motion"}</button><small>© {new Date().getFullYear()} NexTerra</small></footer>
<dialog ref={dialog} className="nt-modal" onCancel={()=>setModal(false)} onClose={()=>setModal(false)} aria-labelledby="nt-contact-title"><button className="nt-modal-close" aria-label="Close dialog" onClick={()=>setModal(false)}><X/></button><div className="nt-eyebrow">LET’S BUILD RESILIENCE</div><h2 id="nt-contact-title">Stay ahead. Together.</h2><p>Explore how connected sensing and AI can support landslide risk monitoring. A contact channel has not yet been configured for this preview.</p><button className="nt-primary" onClick={()=>{setModal(false);document.getElementById("system")?.scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"instant":"smooth"});}}>Explore the system <ArrowUpRight size={16}/></button></dialog></main>;
}


